### PR TITLE
Refactor main function

### PR DESCRIPTION
**Pull request by Gers2017**
Replaces:
- chain of if statements for match statement
- returns Err(String) instead of `std::process:exit()` and `eprinln` (the value inside Err() will be printed)
- open and read file for `fs::read_to_string`

### CODE REVIEW

**Review by usefulmove — COMMENTED** [review]
The match structure is great and leaves much cleaner and readable code! The error handling doesn't maintain the formatting in the error messages. Is this possible using Err(String)?

Screenshot from 2022-07-10 17-40-00

Also, feel free to submit a pull request with the isolated match change to main.

**Comment by Gers2017** [comment]
Apparently rust escapes the color codes.
Moving the contents of main to app makes it easier to print colored errors
For example:

```rs
type ErrorMessage = String;

fn app() -> Result<(), ErrorMessage> {
    let s = "green background".bright_red().on_white();
    let s2 = "works".blue().bold();
    println!("{} {} !", s, s2); // <- works!

    let new_s = format!("{} works?: {}", s, s2);
    println!("{}", new_s); // <- works!

    return Err(new_s);
}

fn main() {
    if let Err(e) = app() {
        eprintln!("{}", e);
    }
}
```

I have been thinking about how to simplify error handling.
Currently a message is printed and the program exits. This is fine, but it becomes repetitive over time.
We could follow this pattern and replace `std::process::exit()` + `eprintln!` completely.

```rs
fn drop(list: &mut Vec<i32>) -> Result<(), ErrorMessage> {
    if list.is_empty() {
        let message = format!(
            "{}: {}",
            "error".bright_red(),
            "operation called on empty stack".bright_yellow()
        );
        return Err(message);
    }
    list.pop();
    Ok(())
}

fn app() -> Result<(), ErrorMessage> {
    let s = "green background".bright_red().on_white();
    let s2 = "works".blue().bold();
    println!("{} {} !", s, s2);

    let new_s = format!("{} works?: {}", s, s2);
    println!("{}", new_s);

    let mut list = vec![];
    drop(&mut list)?; // ? will return the error immediately

    return Err(new_s);
}
```

**Comment by usefulmove** [comment]
Yes, I think this pattern is a very interesting approach. The current structure for most of the stack checks is similar to `c_add` below where a stack check is performed with `Interpreter::check_stack_error` (which halts execution if there is a a check fails) and a `pop_stack` call is made to pop a value of the stack and perform a parse check (also halts execution if it fails).

(`drop` is a bit of an odd case because it doesn't throw an error if the stack is empty. It just prints a warning and continues execution.)

Halting execution is still done with `process::exit` though. To me, this seems clearer, but I may be missing something important here.

```rust
fn c_add(&mut self, op: &str) {
    Interpreter::check_stack_error(self, 2, op);

    let b: f64 = self.pop_stack_f();
    let a: f64 = self.pop_stack_f();

    self.stack.push((a + b).to_string());
}
```

```rust
// confirm stack depth
fn check_stack_error(&self, min_depth: usize, command: &str) {
    if self.stack.len() < min_depth {
        eprintln!(
            "{}: [{}] operation called without at least {min_depth} element(s) on stack",
            "error".bright_red(),
            command.to_string().cyan()
        );
        std::process::exit(99);
    }
}
```

```rust
fn pop_stack_f(&mut self) -> f64 {
    let element: String = self.stack.pop().unwrap();
    match self.parse_float(&element) {
        Ok(val) => val, // parse success
        Err(_error) => { // parse fail
            eprintln!(
                "{}: unknown expression [{}] is not a recognized operation or valid value (f)",
                "error".bright_red(),
                element.cyan()
            );
            std::process::exit(99);
        }
    }
}
```

**Comment by Gers2017** [comment]
As I see it, there are two options: print and exit the program or keep raising the errors until it gets to the main function

## The print and exit route
```rs
// lib.rs
pub fn eprint_and_exit(message: String) {
    eprintln!("{}: {}", "error".bright_red().bold(), message);
    std::process::exit(1);
}

// variant of eprint_and_exit
pub fn eprint_and_exit_with_code(message: String, code: i32) {
    eprintln!("{}: {}", "error".bright_red().bold(), message);
    std::process::exit(code);
}

// main.rs
```rs
fn main() {
    let mut list = vec![];
    add(&mut list);
}

fn add(list: &mut Vec<i32>) {
    check_stack_capacity(list, min_depth, "add")

    let f = list.pop().unwrap();
    let d = list.pop().unwrap();
    list.push(f + d);
}

fn check_stack_capacity(stack: &Vec<i32>, min_depth: usize, command: &str) {
    if stack.len() < min_depth {
        let message = format!(
            "{}: [{}] operation called without at least {min_depth} element(s) on stack",
            "error".bright_red(),
            command.to_string().cyan()
        );
        eprint_and_exit(message);
    }
}
```

## The raise error route
```rs
type ErrorMessage = String;

fn main(){
    if let Err(e) = app() {
        eprintln!("{}", e); // finally print the error
    }
}


fn app() -> Result<(), ErrorMessage> {
    let mut list = vec![];
    add(&mut list)?; // raise error
    Ok(())
}

fn add(list: &mut Vec<i32>) -> Result<(), ErrorMessage> {
    let min_depth = 2;
    check_stack_capacity(list, min_depth, "add")?; // raise error

    let f = list.pop().unwrap();
    let d = list.pop().unwrap();
    list.push(f + d);

    Ok(())
}

fn check_stack_capacity(stack: &Vec<i32>, min_depth: usize, command: &str) -> Result<(), ErrorMessage> {
    if stack.len() < min_depth {
        let message = format!(
            "{}: [{}] operation called without at least {min_depth} element(s) on stack",
            "error".bright_red(),
            command.to_string().cyan()
        );
        Err(message) // raise error
    } else {
        Ok(())
    }
}
```
in the meantime I'll update the pr to isolate the match statement

**Comment by usefulmove** [comment]
This is very helpful. I'm a fan of the first (print and exit) approach. I would also wrap the `unwrap()` calls in `pop_stack_f()` from my previous comment (or similar) to catch parsing errors.

**Review by usefulmove — APPROVED** [review]

**Comment by usefulmove** [comment]
Thank you, @Gers2017! This is great!

**Pull request merged**
